import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactToast from "@/components/react-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2 className="bg-yellow-300">Main Layout</h2>
        {/* <Navbar /> */}
        <ReactToast />
        {children}
      </body>
    </html>
  );
}
