import React from 'react'

const Users = () => {
    return (
        <div>Users Here</div>
    )
}

export default Users

export const generateMetadata = () => {
    return {
        title: "Zaman WebDev Website",
        description: "Generated by Zaman WebDev",
    }
}